### WARNING 
## Self generated file 
# Please do not edit this file # 
## 
### 

class Tree():
    def __init__(self):
        pass

    def decision(self, root, inte):
        classe = None
        try:
            sqft_living = inte.show(root, classe, 'sqft_living')
            if sqft_living <= 1405.0:
                price = inte.show(root, classe, 'price')
                if price <= 270500.0:
                    if sqft_living <= 1075.0:
                        if price <= 227775.0:
                            if sqft_living <= 735.0:
                                inte.format_response("Cara")
                                return inte.show(root, classe, None)
                            else:  # if self.sqft_living > 735.0
                                inte.format_response("Barata")
                                return inte.show(root, classe, None)
                        else:  # if self.price > 227775.0
                            inte.format_response("Cara")
                            return inte.show(root, classe, None)
                    else:  # if self.sqft_living > 1075.0
                        inte.format_response("Barata")
                        return inte.show(root, classe, None)
                else:  # if self.price > 270500.0
                    sqft_lot = inte.show(root, classe, 'sqft_lot')
                    if sqft_lot <= 1263.0:
                        if sqft_living <= 1255.0:
                            inte.format_response("Cara")
                            return inte.show(root, classe, None)
                        else:  # if self.sqft_living > 1255.0
                            inte.format_response("Barata")
                            return inte.show(root, classe, None)
                    else:  # if self.sqft_lot > 1263.0
                        if sqft_lot <= 17688.0:
                            inte.format_response("Cara")
                            return inte.show(root, classe, None)
                        else:  # if self.sqft_lot > 17688.0
                            inte.format_response("Barata")
                            return inte.show(root, classe, None)
            else:  # if self.sqft_living > 1405.0
                price = inte.show(root, classe, 'price')
                if price <= 332500.0:
                    inte.format_response("Barata")
                    return inte.show(root, classe, None)
                else:  # if self.price > 332500.0
                    if sqft_living <= 1700.0:
                        if price <= 355450.0:
                            if sqft_living <= 1470.0:
                                inte.format_response("Cara")
                                return inte.show(root, classe, None)
                            else:  # if self.sqft_living > 1470.0
                                inte.format_response("Barata")
                                return inte.show(root, classe, None)
                        else:  # if self.price > 355450.0
                            sqft_basement = inte.show(root, classe, 'sqft_basement')
                            if sqft_basement <= 630.0:
                                inte.format_response("Cara")
                                return inte.show(root, classe, None)
                            else:  # if self.sqft_basement > 630.0
                                inte.format_response("Media")
                                return inte.show(root, classe, None)
                    else:  # if self.sqft_living > 1700.0
                        if price <= 431500.0:
                            inte.format_response("Barata")
                            return inte.show(root, classe, None)
                        else:  # if self.price > 431500.0
                            if sqft_living <= 2160.0:
                                inte.format_response("Cara")
                                return inte.show(root, classe, None)
                            else:  # if self.sqft_living > 2160.0
                                inte.format_response("Barata")
                                return inte.show(root, classe, None)
        except:
            print('Janela Fechada! Encerrando aplicação...')
            return 0
